# ~/.config/starship.toml

# Inserts a blank line between shell promts
add_newline = true

# Replace the "" symbol in the prompt with "$"
[character]
success_symbol = "[](bold green)"
error_symbol = "[](bold red)"

[python]
symbol = ""

